// v0.12 測試：成就（舊存檔靜默補登、成就頁、新達成提示、英文）
import { createRequire } from 'module';
import { nav } from './e2e-nav.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { playthrough } from './sim-lib.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || '/opt/npm-tools/node_modules/playwright');
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const entry = process.argv[2] || 'index.html';
const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' };
const { s } = playthrough({ talents: true });
s.lastSeen = Date.now(); s.idle = null; s.gold = 60000; s.player = { pid: 'abcdefgh1234', name: '測試', asked: true, playSec: 0 };
s.stats.wins = 99; delete s.ach;
const browser = await chromium.launch(); const page = await browser.newPage({ viewport: { width: 375, height: 760 }, deviceScaleFactor: 2 }); await page.addInitScript(() => sessionStorage.setItem('rl-title', '1'));
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.addInitScript(v => { if (!sessionStorage.getItem('seeded')) { localStorage.setItem('raid-leader-save-v1', v); sessionStorage.setItem('seeded', '1'); } }, JSON.stringify(s));
await page.route('**/*', r => { const u = new URL(r.request().url()); if (u.host !== 'app.test') return r.abort();
  const f = path.join(root, u.pathname === '/' ? entry : u.pathname.slice(1));
  return r.fulfill({ body: fs.readFileSync(f), contentType: types[path.extname(f)] }); });
await page.goto('https://app.test/'); await page.waitForTimeout(1200);
const fails = [], check = (ok, msg) => { console.log((ok ? '✅ ' : '❌ ') + msg); if (!ok) fails.push(msg); };
const shot = n => (process.env.SHOTS || '/tmp/claude-0') + '/' + n;
const toastText = () => page.locator('#toast').innerText().catch(() => '');
check(!(await toastText()).includes('成就'), '舊存檔補登不跳提示');
let sv = await page.evaluate(() => JSON.parse(localStorage.getItem('raid-leader-save-v1')));
await page.click('[data-tab="team"]'); await page.waitForTimeout(200);
const btn = await page.locator('.achbtn').innerText();
check(/成就 \d+ 點/.test(btn) && !btn.includes(' 0 點'), '團隊頁成就按鈕：' + btn);
await page.click('.achbtn'); await page.waitForTimeout(200);
check(await page.locator('.ach').count() > 3, '成就頁有清單：' + await page.locator('.ach').count());
check(await page.locator('.ach.ok').count() >= 3, '已完成：' + await page.locator('.ach.ok').count());
await page.screenshot({ path: shot('ach.png') });
await page.click('[data-act="achcat"][data-v="mythic"]'); await page.waitForTimeout(150);
check((await page.locator('.sheet').innerText()).includes('鑰石收藏家'), '切到秘境分類');
await page.click('[data-act="close-settings"]');
// 第 100 場勝利 → 跳成就提示
await page.click('[data-tab="dungeon"]'); await nav(page, 'story0'); await page.click('.dg [data-act="fight"][data-d="0"]'); await page.waitForTimeout(400);
await page.click('[data-act="skip"]'); await page.waitForTimeout(900);
check((await toastText()).includes('百戰'), '新成就提示：' + await toastText());
sv = await page.evaluate(() => JSON.parse(localStorage.getItem('raid-leader-save-v1')));
check(!!sv.ach.done.wins100, '存檔記錄成就時間');
// 英文
await page.evaluate(() => localStorage.setItem('raid-leader-lang', 'en')); await page.reload(); await page.waitForTimeout(600);
await page.click('[data-tab="team"]'); await page.click('.achbtn'); await page.waitForTimeout(200);
check((await page.locator('.sheet').innerText()).includes('Achievements'), '英文成就頁');
check(!errs.length, '無 JS 錯誤 ' + errs.join(';'));
await browser.close();
if (fails.length) process.exit(1);
