// v0.11 測試：圖示（職業、裝備、首領、金幣、戰鬥紀錄）有畫出來，且沒有殘留 emoji
import { createRequire } from 'module';
import { nav } from './e2e-nav.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { playthrough } from './sim-lib.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || '/opt/npm-tools/node_modules/playwright');
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const entry = process.argv[2] || 'index.html';
const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' };
const G = await import('../src/core/index.js');
const { s } = playthrough({ talents: true });
s.lastSeen = Date.now(); s.idle = null; s.gold = 60000; s.player = { pid: 'abcdefgh1234', name: '測試', asked: true, playSec: 0 };
const sh = G.makeHero('shaman', 20, 4); sh.name = '卡洛'; sh.spec = 'elemental'; s.heroes.push(sh);
const browser = await chromium.launch(); const page = await browser.newPage({ viewport: { width: 375, height: 760 }, deviceScaleFactor: 2 }); await page.addInitScript(() => sessionStorage.setItem('rl-title', '1'));
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.addInitScript(v => { if (!sessionStorage.getItem('seeded')) { localStorage.setItem('raid-leader-save-v1', v); sessionStorage.setItem('seeded', '1'); } }, JSON.stringify(s));
await page.route('**/*', r => { const u = new URL(r.request().url()); if (u.host !== 'app.test') return r.abort();
  const f = path.join(root, u.pathname === '/' ? entry : u.pathname.slice(1));
  return r.fulfill({ body: fs.readFileSync(f), contentType: types[path.extname(f)] }); });
await page.goto('https://app.test/'); await page.waitForTimeout(500);
await page.click('[data-act="dtoggle"]').catch(() => {});
const fails = [], check = (ok, msg) => { console.log((ok ? '✅ ' : '❌ ') + msg); if (!ok) fails.push(msg); };
const shot = n => (process.env.SHOTS || '/tmp/claude-0') + '/' + n;
const EMOJI = /[🛡️✨🗡️🔥🌿⚡👑👾]/u;
check(await page.locator('.dg .tier .gi').count() >= 7, '副本卡有首領圖示：' + await page.locator('.dg .tier .gi').count());
check(await page.locator('.coin').evaluate(el => getComputedStyle(el).maskImage || getComputedStyle(el).webkitMaskImage).then(v => v && v.includes('svg')), '金幣改成圖示');
await page.screenshot({ path: shot('icons-dungeon.png') });
await page.click('[data-tab="team"]'); await page.waitForTimeout(200);
check(await page.locator('.hero .ic .gi').count() >= 5, '團隊頁職業圖示：' + await page.locator('.hero .ic .gi').count());
check(!EMOJI.test(await page.locator('main').innerText()), '團隊頁沒有職業 emoji');
await page.screenshot({ path: shot('icons-team.png') });
await page.locator('.hero').first().click(); await page.waitForTimeout(200);
check(await page.locator('.sheet .gearrow .gi').count() >= 4, '裝備欄有部位圖示：' + await page.locator('.sheet .gearrow .gi').count());
await page.screenshot({ path: shot('icons-sheet.png') });
await page.click('.scrim', { position: { x: 5, y: 5 } });
await page.click('[data-tab="bag"]'); await page.waitForTimeout(200);
await page.screenshot({ path: shot('icons-bag.png') });
await page.click('[data-tab="dungeon"]'); await nav(page, 'story0'); await page.click('.dg [data-act="fight"][data-d="6"]'); await page.waitForTimeout(400);
await page.click('[data-act="speed"][data-x="4"]').catch(() => {}); await page.waitForTimeout(5000);
check(await page.locator('.unit .ic .gi').count() >= 6, '戰鬥單位有圖示：' + await page.locator('.unit .ic .gi').count());
check(await page.locator('.log .gi').count() > 0, '戰鬥紀錄裡的職業圖示');
await page.screenshot({ path: shot('icons-battle.png') });
check(!errs.length, '無 JS 錯誤 ' + errs.join(';'));
await browser.close();
if (fails.length) process.exit(1);
