// v0.7.4 測試：秘境掛機（按鈕、鑰石不變、自動再開、鎖陣容）、巔峰顯示、精煉＋精華、離線秘境掛機結算
import { createRequire } from 'module';
import { nav } from './e2e-nav.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { playthrough } from './sim-lib.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || '/opt/npm-tools/node_modules/playwright');
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const entry = process.argv[2] || 'index.html';
const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' };
const { s } = playthrough({ talents: true });
s.lastSeen = Date.now(); s.idle = null; s.gold = 60000; s.player = { pid: 'abcdefgh1234', name: '測試', asked: true, playSec: 0 };
s.party = s.heroes.slice(0, 5).map(h => h.id);
for (const h of s.heroes) { h.level = 40; h.xp = 0; h.para = 3; h.paraXp = 100; }
s.idle = null; s.mythic.best = { 0: { level: 4, time: 120 } }; s.mythic.key = 7; s.dust = 100;
const p0 = s.heroes.find(h => h.id === s.party[0]); s.items[p0.gear.weapon].up = 5;
// 先在 Node 驗證離線秘境掛機結算
const off = JSON.parse(JSON.stringify(s)); off.idleMythic = 0; off.lastSeen = Date.now() - 2 * 3600e3;
const G = await import('../src/core/index.js');
const r = G.offlineProgress(off);
const offOk = r && r.runs > 10 && off.mythic.key === 7;
const browser = await chromium.launch(); const page = await browser.newPage({ viewport: { width: 375, height: 760 } }); await page.addInitScript(() => sessionStorage.setItem('rl-title', '1'));
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.addInitScript(v => { if (!sessionStorage.getItem('seeded')) { localStorage.setItem('raid-leader-save-v1', v); sessionStorage.setItem('seeded', '1'); } }, JSON.stringify(s));
await page.route('**/*', r => { const u = new URL(r.request().url()); if (u.host !== 'app.test') return r.abort();
  const f = path.join(root, u.pathname === '/' ? entry : u.pathname.slice(1));
  return r.fulfill({ body: fs.readFileSync(f), contentType: types[path.extname(f)] }); });
await page.goto('https://app.test/'); await page.waitForTimeout(500);
const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem('raid-leader-save-v1')));
const toastText = async () => (await page.locator('#toast').innerText().catch(() => '')).trim();
const fails = [], check = (ok, msg) => { console.log((ok ? '✅ ' : '❌ ') + msg); if (!ok) fails.push(msg); };
const shot = n => (process.env.SHOTS || '/tmp/claude-0') + '/' + n;
check(offOk, `離線秘境掛機 2 小時：${r && r.runs} 場、勝 ${r && r.wins}、+${r && r.gold} 金、鑰石仍 +${off.mythic.key}`);
await page.click('[data-tab="dungeon"]'); await nav(page, 'mythic');
const idleBtns = page.locator('.mythic [data-act="idlemythic"]');
check(await idleBtns.count() === 1 && (await idleBtns.first().innerText()).includes('+2'), '只有限時過的副本有掛機按鈕：' + await idleBtns.first().innerText());
await page.locator('.mythic').screenshot({ path: shot('m74-mythic.png') });
await idleBtns.first().click(); await page.waitForTimeout(300);
let sv = await saved();
check(sv.idleMythic === 0 && await page.locator('#idleChip').isVisible(), '開始秘境掛機｜' + await toastText());
check((await page.locator('.bhead h2').innerText()).includes('+2'), '戰鬥等級 +2');
await page.click('[data-act="skip"]'); await page.waitForTimeout(300);
const title = await page.locator('.result h3').innerText();
sv = await saved();
check(title.startsWith('秘境掛機') && sv.mythic.key === 7, '結算：' + title + '｜鑰石 +' + sv.mythic.key);
await page.screenshot({ path: shot('m74-result.png') });
await page.waitForTimeout(4800);
check(!(await page.locator('.result').count()) && (await page.locator('.bhead h2').innerText()).includes('+2'), '3 秒後自動再開');
await page.click('[data-tab="team"]');
check((await page.locator('main').innerText()).includes('陣容已鎖定'), '秘境掛機也鎖陣容');
await page.locator('.party .slot').first().click(); await page.waitForTimeout(200);
check((await page.locator('.sheet').innerText()).includes('巔峰 3'), '巔峰顯示');
const ref = page.locator('.sheet .gearrow [data-act="up"]').first();
const refTxt = await ref.innerText(); await ref.click(); await page.waitForTimeout(200);
sv = await saved();
const w = sv.items[sv.heroes.find(h => h.id === sv.party[0]).gear.weapon];
check(refTxt.includes('精煉') && w.up === 6 && sv.dust === 95, `精煉：${refTxt.replace(/\n/g, ' ')} → +${w.up}、精華 ${sv.dust}｜${await toastText()}`);
await page.screenshot({ path: shot('m74-hero.png') });
await page.click('.scrim', { position: { x: 5, y: 5 } });
await page.click('[data-tab="bag"]');
check((await page.locator('main h2').first().innerText()).includes('精華'), '背包顯示精華');
await page.click('[data-tab="dungeon"]'); await nav(page, 'mythic'); await page.click('.mythic [data-act="idlemythic"]'); await page.waitForTimeout(200);
check((await saved()).idleMythic == null, '停止秘境掛機｜' + await toastText());
check(!errs.length, '無 JS 錯誤 ' + errs.join(';'));
await browser.close();
if (fails.length) process.exit(1);
